--- #YAML:1.0
name:               Cisco-UCS-Common-SwitchCard
version:            0.2
abstract:           Class for operations with a Cisco UCS switch card.
author:
    - Luke Poskitt <ltp@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cisco::UCS::Common::EthernetPort:  0
    Scalar::Util:         0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
